#!/usr/bin/env bash
# This script transfers a file from the client to a server using scp.

if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

file_path=$1
server_ip=$2
username=$3
ssh_key_path=$4

# Use scp to transfer the file to the server's home directory
scp -o StrictHostKeyChecking=no -i "$ssh_key_path" "$file_path" "$username@$server_ip":~/

echo "$file_path transferred to $username@$server_ip:~/"