#!/usr/bin/env bash
# generating MySQL dump with creation of  compressed archive out of it
name=$(date +"%d-%m-%Y")
mysqldump --user=root --password="$1" --all-databases > backup.sql
tar -cvzf "$name".tar.gz backup.sql
